In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import pickle
from pandas_profiling import ProfileReport
import numpy as np

In [6]:
# Read the csv file

df = pd.read_csv(r'C:\Users\anand\Drubh - August ML\Advertising.csv')

In [7]:
df

Unnamed: 0     TV  Radio  Newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [8]:
# find the total no of rows and columns details

df.shape

(200, 5)

In [9]:
# see first 5 rows from the input dataset

df.head()

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [10]:
# see last 5 rows from the dataset

df.tail()

Unnamed: 0     TV  Radio  Newspaper  Sales
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

In [ ]:
# build a model which can predict a sales column
# if I am advertising on TV, radio, newspaper, tell me which mode is more affective
# Define a raltionship - is dataset showing linear or non linear , multicolinear
# Build a model

In [11]:
# find the 5 number summary

df.describe()

# from plots we can see if we increase TV advertising cast, its increasing sales
# its a positivly corelated with Sales

Unnamed: 0          TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000  200.000000
mean   100.500000  147.042500   23.264000   30.554000   14.022500
std     57.879185   85.854236   14.846809   21.778621    5.217457
min      1.000000    0.700000    0.000000    0.300000    1.600000
25%     50.750000   74.375000    9.975000   12.750000   10.375000
50%    100.500000  149.750000   22.900000   25.750000   12.900000
75%    150.250000  218.825000   36.525000   45.100000   17.400000
max    200.000000  296.400000   49.600000  114.000000   27.000000

In [13]:
# look for a relationship

pf = ProfileReport(df)

In [14]:
pf.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [15]:
# check if there is any multicoliearity bwtween independent variables -There is
# no multicolinerarity between this dataset columns

In [17]:
# save the report to  a html

pf.to_file('Advertising report.html')

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
# Select the feature and label i.e X and y

# lets build a basic modle between TV and Sales

In [18]:
df

Unnamed: 0     TV  Radio  Newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [30]:
# select only TV
# creating a x with 2D input two time square brakcet as scikit learn takes
# 2d input while fitting the model
x = df[["TV"]]

In [31]:
x

TV
0    230.1
1     44.5
2     17.2
3    151.5
4    180.8
..     ...
195   38.2
196   94.2
197  177.0
198  283.6
199  232.1

[200 rows x 1 columns]

In [27]:
y = df.Sales

In [28]:
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: Sales, Length: 200, dtype: float64

In [25]:
# lets build a model with TV and Sales

In [29]:
from sklearn.linear_model import LinearRegression

linear = LinearRegression()

# LinearRegression is c class and here we have created a object called linear for this class

In [32]:
# below code will find the values of m and c. It will have only m and c value

linear.fit(x,y)  

# using object - linear we are trying to call fit method of Linearregression class

LinearRegression()

In [33]:
# lets see the c value

linear.intercept_

7.032593549127695

In [36]:
# lets see the m / slope value

linear.coef_

array([0.04753664])

# lets wirte the equation

sales = mTV + c

sales = 0.0475TV + 7.0325

suppoese is spend 10$ for TV

sales = 0.0475*10 + 7.0325

sales = 7.5

In [37]:
# save the model to a file

file = 'linear_reg.sav'

pickle.dump(linear,open(file,'wb'))

In [39]:
# lets do some predictions . pass input as 2d (use 2square brakets )

linear.predict([[45]])

# i.e if we are spending aroung 45 $on TV , in that case slaes will be equal to 9.17

# y = 0.0475*45 + 7.0325 = 9.1717

array([9.17174237])

In [40]:
# Lets predict for multiple inputs

l = [4,5,6,7,89,34,45,67,23]

In [41]:
for i in l :
    print(linear.predict([[i]]))
    
    

[7.22274011]
[7.27027675]
[7.31781339]
[7.36535003]
[11.26335455]
[8.64883932]
[9.17174237]
[10.21754846]
[8.12593628]


In [42]:
# as we have saved our model in linear_reg.sav file, lets try to do predictions using this file

saved_model = pickle.load(open(file,'rb'))

In [43]:
# pass the data to saved model

saved_model.predict([[45]])

# so we can share this modle to others and they can directly use this model to predcit by passing the values

array([9.17174237])

In [44]:
# what is the accuarcy of this model? lets find it out

In [45]:
linear.score(x,y)   # R square , see the details about score fucniton by using shift tab 

0.611875050850071

In [ ]:
https://archive.ics.uci.edu/ml/machine-learning-databases/00601/

## Multiliear regression

Considering more than one independent features

whether Linear regression is a low bias and high variance model?

or high bias and low variance model?

bias - error

variance - disperssion

whenever we are trying to build a model , it will try to understand a relationship between the features and it will try to  adjust itself

error - is nothing but difference between y and y hat(predicted)

By defualt Linear Regression is going to be a high bias and low  variance
kind of model.

bias - is kind of error that we will recive during training.
low variacne -  interms of adjustment of the best fit line when more data is added

In [ ]:
# Multilinear model - multiple indepenedt features and one target label

x will be more columns and y will be only one

In [ ]:
# in above model we took only one feature TV
# now lets consider TV, radio and Newspaper for x

In [46]:
data_x = df[['TV','Radio', 'Newspaper' ]]

In [47]:
data_x

TV  Radio  Newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [48]:
y = df.Sales

In [49]:
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: Sales, Length: 200, dtype: float64

In [50]:
# create a object of LinearRegression class and call the fit method via the object

lm = LinearRegression()
lm.fit(data_x,y)

LinearRegression()

In [51]:
# see intercept or c value
lm.intercept_ 

2.938889369459412

In [52]:
# check m or coeficient value

lm.coef_

array([ 0.04576465,  0.18853002, -0.00103749])

# the equation will look like

y = 0.045TV + 0.1885Radio + (-0.00103Newspaper) + 2.9388

ie

y = x1m1 + x2m2 + x3y3 +c

if someone asks what is the sales i am going to make if i spend $ on TV, Radio and Newspaper. Then put those $ values in the above equation and find the sales/y


# what is the confidence of this model

 confidence - means out of 100 data , for how many data this model is going to correct answer

for example for 100 data if model is giving correct predictions for 90 datapoints then its confidenc is 90% 




In [53]:
lm.score(data_x,y)

# so when we are considering TV, Radio and Newspaper the confidenc is 89%
# when we condiered only TV then the confidence was 61% . so can say its good 
# to condier multiple features

0.8972106381789522

In [54]:
# lets consider only TV and Radio and build a new model

In [56]:
data_x2 = df[['TV' ,'Radio']]
y = df.Sales

In [58]:
lm1 = LinearRegression()
lm1.fit(data_x2,y)
lm1.score(data_x2,y)

0.8971942610828957

In [ ]:
# so we can confidence/R square/score is almost same with 2 and 3 featrues. so we can say
# newspaper is not participating not much. total changes in sales that newspaper 
# is not much. impact of newspaper is less on sales

So we need to do a feature selection during EDA to select the features

R square increases with increased no of features.so R square is not a correct method to select the
features. so we go for Adjusted r square

In [59]:
import statsmodels.formula.api as smf
lm2 = smf.ols(formula = 'Sales ~ TV' , data =df).fit()
lm2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.612
Model:                            OLS   Adj. R-squared:                  0.610
Method:                 Least Squares   F-statistic:                     312.1
Date:                Mon, 23 May 2022   Prob (F-statistic):           1.47e-42
Time:                        21:32:33   Log-Likelihood:                -519.05
No. Observations:                 200   AIC:                             1042.
Df Residuals:                     198   BIC:                             1049.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      7.0326      0.458     15.360      0.000       6.130       7.935
TV             0.0475      0.003     17.668      0.000       0.042       0.053
==============================================================================
Omnibus:                        0.531   Durbin-Watson:                   1.935
Prob(Omnibus):                  0.767   Jarque-Bera (JB):                0.669
Skew:                          -0.089   Prob(JB):                        0.716
Kurtosis:                       2.779   Cond. No.                         338.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [60]:
import statsmodels.formula.api as smf
lm2 = smf.ols(formula = 'Sales ~ TV+Radio' , data =df).fit()
lm2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     859.6
Date:                Mon, 23 May 2022   Prob (F-statistic):           4.83e-98
Time:                        21:32:46   Log-Likelihood:                -386.20
No. Observations:                 200   AIC:                             778.4
Df Residuals:                     197   BIC:                             788.3
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      2.9211      0.294      9.919      0.000       2.340       3.502
TV             0.0458      0.001     32.909      0.000       0.043       0.048
Radio          0.1880      0.008     23.382      0.000       0.172       0.204
==============================================================================
Omnibus:                       60.022   Durbin-Watson:                   2.081
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              148.679
Skew:                          -1.323   Prob(JB):                     5.19e-33
Kurtosis:                       6.292   Cond. No.                         425.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [61]:
import statsmodels.formula.api as smf
lm2 = smf.ols(formula = 'Sales ~ TV+Radio+Newspaper' , data =df).fit()
lm2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     570.3
Date:                Mon, 23 May 2022   Prob (F-statistic):           1.58e-96
Time:                        21:33:04   Log-Likelihood:                -386.18
No. Observations:                 200   AIC:                             780.4
Df Residuals:                     196   BIC:                             793.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      2.9389      0.312      9.422      0.000       2.324       3.554
TV             0.0458      0.001     32.809      0.000       0.043       0.049
Radio          0.1885      0.009     21.893      0.000       0.172       0.206
Newspaper     -0.0010      0.006     -0.177      0.860      -0.013       0.011
==============================================================================
Omnibus:                       60.414   Durbin-Watson:                   2.084
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              151.241
Skew:                          -1.327   Prob(JB):                     1.44e-33
Kurtosis:                       6.332   Cond. No.                         454.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [ ]:
# here p value for newspaper is more. it is impacting only 14% on sales. hence
we can ingnore newspaper. 

# like this we can use stats model to check the adj R square, p value and other details
# the column which is having more p value, we can ignore /drop that x variable while
# building the model
# cross validation is one more method used for feature engineering

In [ ]:
# Regularization

Technique used to control the degree of freedom of m and c. i.e controlling the error
term delta Em so that I will be able to generalize my model in a best possible way 
is called as Regulariztion. It is used to avoide overfitting or underfitting
of the model

LASSO- Leaset absolute shrikage and selection operator - one of the regulairation technique
or L1

rIDGE rEGRESSION - L2

eLASTICNET

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge,Lasso,RidgeCV,LarsCV,ElasticNet,ElasticNetCV,LinearRegression
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaboran as sns

In [62]:
df = pd.read_csv("D:\My Downloads\Admission_Prediction.csv")

In [63]:
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0             1      337.0        118.0                4.0  4.5  4.5  9.65   
1             2      324.0        107.0                4.0  4.0  4.5  8.87   
2             3        NaN        104.0                3.0  3.0  3.5  8.00   
3             4      322.0        110.0                3.0  3.5  2.5  8.67   
4             5      314.0        103.0                2.0  2.0  3.0  8.21   
..          ...        ...          ...                ...  ...  ...   ...   
495         496      332.0        108.0                5.0  4.5  4.0  9.02   
496         497      337.0        117.0                5.0  5.0  5.0  9.87   
497         498      330.0        120.0                5.0  4.5  5.0  9.56   
498         499      312.0        103.0                4.0  4.0  5.0  8.43   
499         500      327.0        113.0                4.0  4.5  4.5  9.04   

     Research  Chance of Admit  
0           1             0.92  
1           1             0.76  
2           1             0.72  
3           1             0.80  
4           0             0.65  
..        ...              ...  
495         1             0.87  
496         1             0.96  
497         1             0.93  
498         0             0.73  
499         0             0.84  

[500 rows x 9 columns]

 Requirment -  build a model to predict chance of Admission if I give all x features mentioned above i.e GRE score, TOFEL score, university rating, SOP, LOR etc

In [64]:
# Do the profile reporting

pf = ProfileReport(df)

In [65]:
pf.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]